version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DB: postgres
      DB_HOST: ls-a4e9b0ea6d8ec0b0f5963b949783d404e86778be.cj4aisyocga4.us-east-2.rds.amazonaws.com
      DB_PORT: 5432
      APP_DEBUG: false
      DB_DATABASE: postgres
      DB_USERNAME: dbmasteruser
      DB_PASSWORD: "F~}80=KS[S1^D5&:xPU=pQt[Zq.)!s*z"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"

volumes:
  mongo-data:
  mysql-data: