

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON catalogs.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON catalogs.* TO  root@'%';
FLUSH PRIVILEGES;

USE catalogs;